pull-request: Remove message if editor fails
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>

diff --git a/pdx86-pull-request b/pdx86-pull-request
--- a/pdx86-pull-request
+++ b/pdx86-pull-request
@@ -83,4 +83,9 @@ if [ $? -ne 0 ]; then
 	exit 1
 fi
 vim $MSG +3
+if [ $? -ne 0 ]; then
+	rm $MSG
+	echo "ERROR: message editor failed"
+	exit 1
+fi
 echo "Use 'mutt -H $MSG' to send the pull request."
