pdx86-gen-config: Update for Mellanox platform changes
Update requirements and add the platform/mellanox/KConfig to the files
to scan.

Signed-off-by: Darren Hart (VMware) <dvhart@infradead.org>

diff --git a/pdx86-gen-config b/pdx86-gen-config
--- a/pdx86-gen-config
+++ b/pdx86-gen-config
@@ -6,11 +6,7 @@ MODVALUE="m"
 echo "CONFIG_PCI=y"
 echo "CONFIG_ACPI=y"
 echo "CONFIG_X86_PLATFORM_DEVICES=y"
-
-# Required by MLX_CPLD_PLATFORM
-echo "CONFIG_64BIT=y"
-echo "CONFIG_X86_EXTENDED_PLATFORM=y"
-echo "CONFIG_MLX_PLATFORM=y"
+echo "CONFIG_MELLANOX_PLATFORM=y"
 
 if [ "$1" = "-y" ]; then
 	MODVALUE="y"
@@ -18,22 +14,24 @@ else
 	echo "CONFIG_MODULES=y"
 fi
 
-while IFS='' read -r LINE || [[ -n "$line" ]]; do
-	if [ "${LINE#config }" != "$LINE" ]; then
-		CONFIG=${LINE#config }
-		continue
-	fi
-
-	if [ -n "$CONFIG" ]; then
-		if [[ "$LINE" =~ "bool" ]]; then
-			echo "CONFIG_$CONFIG=y"
-		elif [[ "$LINE" =~ "tristate" ]]; then
-			echo "CONFIG_$CONFIG=$MODVALUE"
-		else
-			echo "Type not found for config \"$CONFIG\""
-			exit 1
+for KCONFIG in drivers/platform/x86/Kconfig drivers/platform/mellanox/Kconfig; do
+	while IFS='' read -r LINE || [[ -n "$line" ]]; do
+		if [ "${LINE#config }" != "$LINE" ]; then
+			CONFIG=${LINE#config }
+			continue
 		fi
-	fi
-	unset CONFIG
-done < drivers/platform/x86/Kconfig
+
+		if [ -n "$CONFIG" ]; then
+			if [[ "$LINE" =~ "bool" ]]; then
+				echo "CONFIG_$CONFIG=y"
+			elif [[ "$LINE" =~ "tristate" ]]; then
+				echo "CONFIG_$CONFIG=$MODVALUE"
+			else
+				echo "Type not found for config \"$CONFIG\""
+				exit 1
+			fi
+		fi
+		unset CONFIG
+	done < $KCONFIG
+done
 
