start: Fail gracefully if pwclient is missing
Rather than dump the output of which to the console, provide consistent
Status headers and an error message if pwclient is not found.

Signed-off-by: Darren Hart (VMware) <dvhart@infradead.org>

diff --git a/pdx86-start b/pdx86-start
--- a/pdx86-start
+++ b/pdx86-start
@@ -26,7 +26,14 @@ git fetch $(git config branch.master.remote)  master:master
 pdx86-branch-status
 
 # Report on Patchwork state
-which pwclient > /dev/null && pwclient list -a no -f '%{id} %{state} %{delegate} %{name}'
+echo -e "\nPatchwork Status"
+which pwclient &> /dev/null
+if [ $? -eq 0 ]; then
+	pwclient list -a no -f '%{id} %{state} %{delegate} %{name}'
+else
+	echo "Error: pwclient not found"
+fi
+
 
 # Exit and return to shell
 echo
