pdx86-lock: Show lease time information when the lock is held
If the lock is held by user "test" and someone else attempts to acquire
it, an example result would be:

$ pdx86-lock
ERROR: Lock held by test
Lock acquired by test (For 2 hours)
19 minutes ago
Time remaining on lease: 101 minutes

If the lease had expired, an example result would be:

$ pdx86-lock
ERROR: Lock held by test
Lock acquired by test (For 2 hours)
19 minutes ago
Lease expired: 10 minutes ago

Signed-off-by: Darren Hart (VMware) <dvhart@infradead.org>

diff --git a/pdx86-lock b/pdx86-lock
--- a/pdx86-lock
+++ b/pdx86-lock
@@ -55,7 +55,20 @@ push() {
 
 owner() {
 	if [ ! "$VAL" = "$PDX86_ID" ]; then
-		echo "ERROR: Lock held by $VAL"
+		echo "ERROR: Lock held by $VAL:"
+		git log --pretty=format:"%h %s%n%cr" -1 -- LOCK
+		LOCK_TIME=$(date -d "$(git log --pretty=format:%cI origin/mutex -1 -- LOCK)" +%s)
+		CUR_TIME=$(date +%s)
+		ELAPSED_TIME=$(($CUR_TIME-$LOCK_TIME))
+		LAST_LEASE=$((3600*$(git log --pretty=format:%s -1 -- LOCK | sed -e "s/.*For \([0-9][0-9]*\) hours.*/\1/")))
+		if [ $? -ne 0 ]; then
+			echo "No lease time provided"
+		elif [ $ELAPSED_TIME -lt $LAST_LEASE ]; then
+			echo "Time remaining on lease: $(($(($LAST_LEASE-$ELAPSED_TIME))/60)) minutes"
+		else
+			echo "Lease expired: $(($(($ELAPSED_TIME-$LAST_LEASE))/60)) minutes ago"
+		fi
+
 		clean_up
 		exit $ERR
 	fi
